# Generated by Django 5.2 on 2025-08-04 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0002_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursenode',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed course content in markdown format'),
        ),
        migrations.AddField(
            model_name='coursenode',
            name='course_url',
            field=models.URLField(blank=True, help_text='External link to the course'),
        ),
        migrations.AddField(
            model_name='coursenode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='learning_path.coursenode'),
        ),
    ]
